### ISSUE TITLE
IndexError: index 2000 is out of bounds for dimension 0 with size 2000

### ISSUE THREAD

**Issue by ypsoh** [ypsoh/sparse_training#7]
Traceback (most recent call last):
  File "test_nn.py", line 133, in <module>
    y_pred = model(x_test)
  File "/home/users/ypsoh/anaconda3_x86/envs/dlrm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "test_nn.py", line 30, in forward
    hidden = self.fc1(x)
  File "/home/users/ypsoh/anaconda3_x86/envs/dlrm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/storage/users/ypsoh/Workspace/libxsmm/samples/deeplearning/sparse_training/pcl_mlp/pcl_mlp.py", line 279, in forward
    output =  XsmmFC.apply(input, wtensor, btensor, self.xsmm_handle, self.sparse_kernel_mode)
  File "/storage/users/ypsoh/Workspace/libxsmm/samples/deeplearning/sparse_training/pcl_mlp/pcl_mlp.py", line 42, in forward
    output = pcl_mlp_ext.sparse_forward(handle.handle, input, weight, bias)
IndexError: index 2000 is out of bounds for dimension 0 with size 2000

**Comment by ypsoh** [comment]
The reason behind this issue is that the number of input (N) has to be blocked too so it should be divisible by factors of 64 (blocking factor). I'm not sure if we should zero-pad N as well? Or just make sure the number of batches are fed in to the model in factors of the blocking factor. For now, I'll consider the latter approach.
